version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - main
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/api/prom/push"
  
services:
  homepage:
    <<: *defaults
    build: .
    env_file:
      - ./.env
    
networks:
  main:
    external: true